config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]

  resources :hubs do
    resources :posts, except:[:index] do
      post "upvote", on: :member
      post "downvote", on: :member
      resources :comments, except:[:index] do
        post "upvote", on: :member
        post "downvote", on: :member
      end
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :author_id, presence: true

  belongs_to :author,
  foreign_key: :author_id,
  class_name: 'User'

  belongs_to :post,
  foreign_key: :post_id,
  class_name: 'Post'

  # if this is a nested comment, it will have a parent id
  belongs_to :comment,
  foreign_key: :parent_comment_id,
  class_name: 'Comment'

  has_many :child_comments,
  foreign_key: :parent_comment_id,
  class_name: 'Comment'

  has_many :votes,
  as: :votable

  def vote_count
    self.votes.inject(0){|accum, vote| accum += vote.value}
  end

  def is_top_level_comment?
    self.parent_comment_id.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.post_id = params[:post_id]
    if @comment.save
      redirect_to hub_post_url(params[:hub_id], @comment.post_id)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to hub_post_url(params[:hub_id],params[:id])
    end
  end

  def upvote
    Vote.create!(value: 1, votable_id: params[:id], votable_type: "Comment")
    redirect_to hub_post_url(params[:hub_id],params[:post_id])
  end

  def downvote
    Vote.create!(value: -1, votable_id: params[:id], votable_type: "Comment")
    redirect_to hub_post_url(params[:hub_id],params[:post_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :parent_comment_id)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_section.html.erb
<h3>Comments</h3>
<% post.sorted_comments.each do |comment| %>
  <% if comment.is_top_level_comment? %>
  <p>
    <%= comment.content %><br />
    Author: <%=comment.author.email%>
    <br />
    Vote: <%= comment.vote_count %>
    <%= button_to "Upvote",
        upvote_hub_post_comment_url(params[:hub_id], post.id, comment.id),
        method: :post %>
    <%= button_to "Downvote",
        downvote_hub_post_comment_url(params[:hub_id], post.id, comment.id),
        method: :post %>
    <ul>
      <% @comments_by_parent_id[comment.id].each do |child_comment| %>
        <li>
          <%= child_comment.content %><br />
          by <%= child_comment.author.email %>
        </li>
      <% end %>
    </ul>
    <%= render "comments/form", post: post, parent_comment: comment %>
  </p>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<form action="<%= hub_post_comments_url(params[:hub_id], post.id) %>", method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
  >
  <input
    type="hidden"
    name="comment[author_id]"
    value="<%=current_user.id%>"
  >
<% if parent_comment %>
  <% text = "reply" %>
  <input
    type="hidden"
    name="comment[parent_comment_id]"
    value="<%=parent_comment.id%>"
  >
<% else %>
  <% text = "New Comment" %>
<% end %>

  <label for="comment_content"><%=text%></label>
  <br />
  <textarea name="comment[content]" id="comment_content"></textarea>
  <br />

  <input type="submit">
</form>