config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]

  resources :hubs do
    resources :posts, except:[:index] do
      post "upvote", on: :member
      post "downvote", on: :member
      resources :comments, except:[:index] do
        post "upvote", on: :member
        post "downvote", on: :member
      end
    end
  end

end

app/models/hub.rb
# == Schema Information
#
# Table name: hubs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text             not null
#  author_id   :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Hub < ActiveRecord::Base
  validates :title, :description, :author_id, presence: true

  belongs_to :author,
  foreign_key: :author_id,
  class_name: 'User'

  has_many :post_hubs, dependent: :destroy,
  foreign_key: :hub_id,
  class_name: 'PostHub'

  has_many :posts,
  through: :post_hubs,
  source: :post

  def sorted_posts
     self.posts.sort{ |b,a| a.vote_count <=> b.vote_count }
  end
end

app/controllers/hubs_controller.rb
class HubsController < ApplicationController
  before_action :ensure_logged_in

  def index
    @hubs = Hub.all
    render :index
  end

  def create
    @hub = Hub.new(hub_params)
    @hub.author_id = current_user.id

    if @hub.save
      redirect_to hub_url(@hub.id)
    else
      flash.now[:errors] = @hub.errors.full_messages
      render :new
    end
  end

  def update
    @hub = Hub.find_by_id(params[:id])
    if @hub.update(hub_params)
      redirect_to hub_url(@hub.id)
    else
      flash.now[:errors] = @hub.errors.full_messages
      render :edit
    end
  end

  def destroy
    @hub = Hub.find_by_id(params[:id])
    @hub.destroy
    redirect_to hubs_url
  end

  def new
    @hub = Hub.new
    render :new
  end

  def edit
    @hub = Hub.find_by_id(params[:id])
    render :edit
  end

  def show
    @hub = Hub.find_by_id(params[:id])
    render :show
  end

  private
  def hub_params
    params[:hub].permit(:title, :description)
  end

end

app/helpers/hubs_helper.rb
module HubsHelper
end

app/views/hubs/edit.html.erb
<h1>Edit <%= @hub.title %></h1>

<form
  action="<%=hub_url(@hub.id)%>"
  method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value ="<%= form_authenticity_token%>">
  <input
    type="hidden"
    name="_method"
    value ="patch">

    <label>Title
      <br />
    <input
      type="text"
      name="hub[title]"
      value="<%= @hub.title %>">
    </label>
    <br />

    <label>Description
      <br />
    <textarea
      name="hub[description]"><%=@hub.description%></textarea>
      </label>
      <br />
    <input type="submit" value="Update">
</form>
<%= button_to "Cancel", hubs_url, method: :get%>

app/views/hubs/index.html.erb
<h1>Reddit Clone</h1>
<h2>Trending Hubs</h2>
<body>
  <% @hubs.each do | hub | %>
    <%=link_to "#{hub.title}", hub_url(hub.id) %>
    <br />
  <% end %>
</body>
<br />
<%= button_to "Add a new hub", new_hub_url, method: :get%>

app/views/hubs/new.html.erb
<h1>Create a New Hub!</h1>

<form
  action="<%=hubs_url%>"
  method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value ="<%= form_authenticity_token%>">

    <label>Title
      <br />
    <input
      type="text"
      name="hub[title]"
      value="<%= @hub.title %>">
    </label>
    <br />

    <label>Description
      <br />
    <textarea
      name="hub[description]"></textarea>
      </label>
      <br />
    <input type="submit">
</form>
<%= button_to "Cancel", hubs_url, method: :get%>

app/views/hubs/show.html.erb
<%= link_to "Back to Mainpage", hubs_url %>
<h1><%= @hub.title %></h1>
<%= button_to "Edit Hub", edit_hub_url(@hub.id), method: :get%>
<h4>
  <%= @hub.description %>
</h4>
<br />
<body>
  <ol>
    <% @hub.sorted_posts.each do |post| %>
      <li>
        <%= link_to "#{post.title}", hub_post_url(@hub.id, post.id)%>
        <br />
        Vote: <%= post.vote_count %>
        <%= button_to "Upvote", upvote_hub_post_url(@hub.id, post.id), method: :post%>
        <%= button_to "Downvote", downvote_hub_post_url(@hub.id, post.id), method: :post%>
        <br />
      </li>
    <% end %>
  </ol>
</body>
<br />
<%= button_to "Add New Post", new_hub_post_url(@hub.id), method: :get %>