config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]

  resources :hubs do
    resources :posts, except:[:index] do
      post "upvote", on: :member
      post "downvote", on: :member
      resources :comments, except:[:index] do
        post "upvote", on: :member
        post "downvote", on: :member
      end
    end
  end

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  hub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base

  validates :title, :hub_ids, presence: true

  belongs_to :author,
  foreign_key: :author_id,
  class_name: 'User'

  has_many :post_hubs,
  foreign_key: :post_id,
  class_name: 'PostHub'

  has_many :hubs,
  through: :post_hubs,
  source: :hub

  has_many :comments

  has_many :votes,
  as: :votable

  def comments_by_parent_id
    comment_hash = Hash.new([])
    self.comments.each do |comment|
      unless comment.is_top_level_comment?
        comment_hash[comment.parent_comment_id] += [comment]
      end
    end
    comment_hash
  end

  def vote_count
    self.votes.inject(0){|accum, vote| accum += vote.value}
  end

  def sorted_comments
    self.comments.sort{ |b,a| a.vote_count <=> b.vote_count }
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_logged_in
  before_action :ensure_post_owner, only:[:edit, :update, :destroy]

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    @post.hub_ids = params[:post][:hub_ids]
    if @post.save
      redirect_to hub_post_url(params[:hub_id], @post.id)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def update
    @post = Post.find_by_id(params[:id])
    @post.hub_ids = params[:post][:hub_ids]
    if @post.update(post_params)
      redirect_to hub_post_url(params[:hub_id], params[:id])
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    @post.destroy if @post
    redirect_to hub_url(params[:hub_id])
  end

  def new
    @post = Post.new
    render :new
  end

  def edit
    @post = Post.find_by_id(params[:id])
    render :edit
  end

  def show
    @post = Post.find_by_id(params[:id])
    @comments_by_parent_id = @post.comments_by_parent_id
    render :show
  end

  def upvote
    Vote.create!(value: 1, votable_id: params[:id], votable_type: "Post")
    redirect_to hub_url(params[:hub_id])
  end

  def downvote
    Vote.create!(value: -1, votable_id: params[:id], votable_type: "Post")
    redirect_to hub_url(params[:hub_id])
  end

  private
  def post_params
    params[:post].permit(:title, :url, :content)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Edit <%= @post.title %></h1>

<form
  action="<%=hub_post_url(params[:hub_id], params[:id])%>"
  method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value ="<%= form_authenticity_token%>">
  <input
    type="hidden"
    name="_method"
    value ="patch">

    <label>Title
      <br />
    <input
      type="text"
      name="post[title]"
      value="<%= @post.title %>">
    </label>
    <br />

    <label>Select Hubs
    <br />
      <% Hub.all.each do |hub| %>
      <input
        type="checkbox"
        name="post[hub_ids][]"
        value="<%= hub.id %>"
        <%= "checked" if @post.hub_ids.include?(hub.id)%>>
        <%= hub.title %>
      </input>
      <% end %>
    <br />
    </label>

    <label>Url
      <br />
    <input
      type="text"
      name="post[url]"
      value="<%= @post.url %>">
    </label>
    <br />

    <label>Content
      <br />
    <textarea
      name="post[content]"><%=@post.content%></textarea>
      </label>
      <br />
    <input type="submit" value="Update">
</form>
<%= button_to "Cancel", hub_post_url(params[:hub_id], @post.id), method: :get%>

app/views/posts/new.html.erb
<h1>Create a New Post!</h1>

<form
  action="<%=hub_posts_url(params[:hub_id])%>"
  method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value ="<%= form_authenticity_token%>">

  <label>Title
    <br />
    <input
      type="text"
      name="post[title]"
      value="<%= @post.title %>">
  </label>
  <br />

  <label>Select Hubs
  <br />
    <% Hub.all.each do |hub| %>
    <input
      type="checkbox"
      name="post[hub_ids][]"
      value="<%= hub.id %>">
      <%= hub.title %>
    </input>
    <% end %>
  <br />
  </label>

  <label>Url
  <br />
    <input
      type="text"
      name="post[url]"
      value="<%= @post.url %>">
  </label>
  <br />

  <label>Content
  <br />
    <textarea
      name="post[content]"><%= @post.content %></textarea>
  </label>
  <br />

  <input type="submit">
</form>
<%= button_to "Cancel", hub_url(params[:hub_id]), method: :get%>

app/views/posts/show.html.erb
<%= link_to "Back to #{Hub.find_by_id(params[:hub_id]).title}", hub_url(params[:hub_id]) %>
<h1><%= @post.title %></h1>
<h3>Hub:</h3>
<div id="hub_list">
  <ul>
    <% @post.hubs.each do |hub| %>
      <li><%=hub.title%></li>
    <% end %>
  </ul>
</div>
<h3>Author: <%= @post.author.email %></h3>
<img src="<%= @post.url %>" height="50%" width="50%"></img>
<p>
  <%= @post.content %>
</p>
<div>
  <%= button_to "Edit Post",
    edit_hub_post_url(params[:hub_id], @post.id),
    method: :get
   %>
  <%= button_to "Delete Post",
    hub_post_url(params[:hub_id], @post.id),
    method: :delete
  %>
</div>
<!-- Rendering partial views for comments-->
<%= render "comments/comment_section",
  post: @post,
  comments_by_parent_id: @comments_by_parent_id
%>
<!-- Rendering partial forms for submmiting comments -->
<%= render "comments/form",
  post: @post,
  parent_comment: nil
%>